export const USER_DATA_KEY = 'userData'
export const LOGIN_TOKEN_KEY = 'token'
export const IS_REMEMBER_PW_KEY = 'isRememberpW'
export const USER_INFO_KEY = 'userInfo'
export const USER_MENUS_KEY = 'userMenus'
